version: "3"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: articles
      POSTGRES_PASSWORD: 1234
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: